// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-xCy4DiB1DdPeuwkhqIFaj7BKzPm-RQ',
    appId: '1:191928184869:web:0d40a4cd9ca4b7f03f0fcc',
    messagingSenderId: '191928184869',
    projectId: 'house-vision-6e168',
    authDomain: 'house-vision-6e168.firebaseapp.com',
    storageBucket: 'house-vision-6e168.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1mmHwt3TBZilPP1LHwkSRP8Kz1XBLPs',
    appId: '1:191928184869:android:e9ac524ade9bd6993f0fcc',
    messagingSenderId: '191928184869',
    projectId: 'house-vision-6e168',
    storageBucket: 'house-vision-6e168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Zok4PrNDW58pHxFi6FyZCP052F6ev4M',
    appId: '1:191928184869:ios:182194f603cfc1a33f0fcc',
    messagingSenderId: '191928184869',
    projectId: 'house-vision-6e168',
    storageBucket: 'house-vision-6e168.firebasestorage.app',
    iosBundleId: 'com.example.houseVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Zok4PrNDW58pHxFi6FyZCP052F6ev4M',
    appId: '1:191928184869:ios:182194f603cfc1a33f0fcc',
    messagingSenderId: '191928184869',
    projectId: 'house-vision-6e168',
    storageBucket: 'house-vision-6e168.firebasestorage.app',
    iosBundleId: 'com.example.houseVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb-xCy4DiB1DdPeuwkhqIFaj7BKzPm-RQ',
    appId: '1:191928184869:web:aeb3562cfa6eb3bf3f0fcc',
    messagingSenderId: '191928184869',
    projectId: 'house-vision-6e168',
    authDomain: 'house-vision-6e168.firebaseapp.com',
    storageBucket: 'house-vision-6e168.firebasestorage.app',
  );
}
